### ISSUE TITLE
attribute values with single quotes?

### ISSUE THREAD

**Issue by ruanpienaar** [esl/exml#54]
single quote are causing issues when creating xml.
Xml is being sent to a third party that expects double quotes on attr values. 🤦 

a option to have have attribures with Double/Single quotes would be nice

ex:
```➜  exml git:(master) ✗ erl -pa _build/default/lib/*/ebin 
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]

Eshell V11.0  (abort with ^G)
1> application:ensure_all_started(exml).
{ok,[exml]}
2> exml
exml           exml_nif       exml_query     exml_stream    
2> rr(exml).     
[xmlcdata,xmlel,xmlstreamend,xmlstreamstart]
3> exml:to_binary(#xmlel{ name = <<"test">>, attrs = [{<<"test">>, <<"a">>}], children = []}).
<<"<test test='a'/>">>
4> ```

**Comment by NelsonVides** [comment]
I had a look at how to do such thing, attributes are printed here: https://github.com/esl/exml/blob/9814aa25481b4357a45663f6cb12ff10504aa302/c_src/rapidxml_print.hpp#L120, and specifically the logic for deciding the quote type is here: https://github.com/esl/exml/blob/9814aa25481b4357a45663f6cb12ff10504aa302/c_src/rapidxml_print.hpp#L131

So if the contents of the attribute value contain a single-quote, double quotes will be used to wrap it, so as not having to escape the single-quote. Otherwise, single quotes will be used and any double-quote will be escaped. Which is the most common thing, attribute values rarely would contain any type of quote to begin with.

This logic can be extended to take a parameter that decides the wrapper, but, that'd be out of the scope of our use-case. Keeping this code so performant is not easy C++ code so I'm afraid we won't do the heavy-lifting here. But hopefully these directions can help you out on how to implement such code and, a PR would be more than welcome 🙃
